### ISSUE TITLE
feedback.js bug

### ISSUE THREAD

**Issue by gqoew** [spektom/bootstrap-feedback-form#4]
Hello,

Thanks for open-sourcing this useful little form!

When I click on the send button, I have this error: `undefined is not a function (near '...$.ajax...')`. I used the original `feedback.js` script. I am using `https://code.jquery.com/jquery-3.2.1.slim.min.js`.

Can you help with my issue? Thanks 🙂

**Comment by mispecto** [comment]
See this:
https://stackoverflow.com/questions/44212202/my-javascript-is-returning-this-error-ajax-is-not-a-function/44212249

**Comment by gqoew** [comment]
Works great now! Thanks 👍
